### PR TITLE
Work under version managing

### PR DESCRIPTION
**Pull request by avengerweb**
Work under version managing
Move dbc achievement to controller

### CODE REVIEW

**Comment by Helias** [comment]
In the api config, if I set "wotlk" as default, I can still make some request about wod contents?

**Comment by avengerweb** [comment]
If u setting "wotlk" as default, when u request without "version" param u get wotlk data, else if u has something like "?version=wod" u get wod data

**Comment by FrancescoBorzi** [comment]
does it work also with "?version=6"  ?  we need that for backward compatibility

**Comment by avengerweb** [comment]
Yes, here is example:
https://github.com/ShinDarth/TC-JSON-API/pull/13/commits/cef00b36efffa99afb0b82f6f51964bfee5ad12a#diff-2bdca63580d2396554492863548bafedR17

U can use: version=wod or version=6 or version=6.x.x

**Comment by FrancescoBorzi** [comment]
@avengerweb thank you!

**Pull request merged**
